cache:
  paths:
  - vendor/

before_script:
  - bash .gitlab-ci.sh

test:5.5:
  image: php:5.5
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

test:5.6:
  image: php:5.6
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

test:7.0:
  image: php:7.0
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

test:7.1:
  image: php:7.1
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php
