cache:
  paths:
  - vendor/

before_script:
  - bash .gitlab-ci.sh

stages:
  - test
  - trigger

test:5.5:
  stage: test
  image: php:5.5
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

test:5.6:
  stage: test
  image: php:5.6
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

test:7.0:
  stage: test
  image: php:7.0
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

test:7.1:
  stage: test
  image: php:7.1
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

test:7.2:
  stage: test
  image: php:7.2
  script:
    - php vendor/bin/phpunit
    - php vendor/bin/phpcs --standard=PSR2 -n lib tests *.php

trigger:
  image: php:7.2
  stage: trigger
  script:
    # Tribber fedapay-checkout
    - curl -X POST -F token=$FEDAPAY_CHECKOUT_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/5338775/trigger/pipeline
  only:
    - develop
    - master
